### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by cmandlbaur** [Aurel300/docopt.hx#1]
Not sure if this is ready for general consumption yet, but I am about to try using it for a project I am working on.

Would be great if it was published to haxelib and posted on the [docopt org page](https://github.com/docopt) for visibility.

**Comment by Aurel300** [comment]
I did open an issue on the docopt repo (https://github.com/docopt/docopt/issues/391), but I have not yet received a reply. I can publish on haxelib though.

Out of curiosity – any reason you don't like to use `haxelib git`?

**Comment by Aurel300** [comment]
@cmandlbaur Just published: http://lib.haxe.org/p/docopt/0.6.2/

Let me know if it works.

**Comment by cmandlbaur** [comment]
No reason that I'm against git, just nice to have it published to a registry too.

I have tried it, but didnt have much luck.

I had to install the nightly to get it building with arrow functions, once that was working it was failing for me on `parseSeq()`. The check in the while loop wasn't catching if `tokens.current()` is `null`.

I added an additional check within the while loop for null to break the loop and return. This got me further, but I still had errors.

Not sure if these were due to regressions in the nightly or bug within lib code.

**Comment by cmandlbaur** [comment]
What version of the compiler are you using?

**Comment by Aurel300** [comment]
Oh darn, I did forget about the arrow functions. I intended to get rid of those before publishing. I will fix this shortly. I'm using a build from June 2017.

**Comment by Aurel300** [comment]
Ok, I pushed to Git, I won't submit to haxelib until it's all sorted out. I removed the arrow functions. However, the check in `parseSeq` seems to be working fine, even on try.haxe.org. What does your compiler give here?

    var cur = null;
    trace([null, "]", ")", "|"].indexOf(cur));

Also, what is the docstring / usage you are using? Are you passing in the arguments yourself?

**Comment by cmandlbaur** [comment]
I was following the example given in the Readme. Will retry now and let you know.

**Comment by cmandlbaur** [comment]
Took the example on the Readme verbatim and still get an error. My guess is that its maybe because I am using it with js running in node and the check is only for `null`, but the value of the current token is `undefined`.

Heres the stack trace:
```
/Users/Chris/Proj/bin/cli.js:505
        if(s.length >= start.length) {
     ^
TypeError: Cannot read property 'length' of undefined
    at Function.StringTools.startsWith (/Users/Chris/Proj/bin/cli.js:505:6)
    at Function.org_docopt_Docopt.parseAtom (/Users/Chris/Proj/bin/file:/Users/Chris/Proj/.haxelib/docopt/git/src/org/docopt/Docopt.hx:424:14)
    at Function.org_docopt_Docopt.parseSeq (/Users/Chris/Proj/bin/file:/Users/Chris/Proj/.haxelib/docopt/git/src/org/docopt/Docopt.hx:380:17)
    at Function.org_docopt_Docopt.parseExpr (/Users/Chris/Proj/bin/cli.js:4917:27)
    at Function.org_docopt_Docopt.parsePattern (/Users/Chris/Proj/bin/file:/Users/Chris/Proj/.haxelib/docopt/git/src/org/docopt/Docopt.hx:346:13)
    at Function.org_docopt_Docopt.parse (/Users/Chris/Proj/bin/file:/Users/Chris/Proj/.haxelib/docopt/git/src/org/docopt/Docopt.hx:214:26)
    at Function.proj_Main.main (/Users/Chris/Proj/bin/file:/Users/Chris/Proj/src/proj/Main.hx:54:32)
    at /Users/Chris/Proj/bin/cli.js:5711:19
    at Object.<anonymous> (/Users/Chris/Proj/bin/cli.js:5712:3)
    at Module._compile (module.js:569:30)
```

Will try track it down a bit more.

**Comment by cmandlbaur** [comment]
Yup its JS causing some pain around `null` vs `undefined`.
```javascript
[null,"]",")","|"].indexOf(undefined) == -1; // true, should be false for code to work.
undefined == null; // true, which is why an if check and break in the loop worked.
```

**Comment by Aurel300** [comment]
Ah, okay. I haven't actually tested with JS. The way it is written (`[null, "]", ")", "|"].indexOf(token) == -1`) is  very Pythonic, but I didn't want to make large deviations from the reference implementation for no reason.

The `null` check should only ever come true when the `Tokens` array has no more tokens to give, so I replaced it with an array length check. This should work fine on JS.

I'll update the haxelib version as well if this solves the problem.

**Comment by cmandlbaur** [comment]
Great, that seems to have fixed the issue. Now works with the default example. Will work on using it with my app now and let you know if there are any other issues that come up.
